// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGIXhG6u8XiM7TJ9EoPrR8krVCAJLCH_E',
    appId: '1:278339723370:web:9b4e93d193216ac810ea13',
    messagingSenderId: '278339723370',
    projectId: 'ff-frontline',
    authDomain: 'ff-frontline.firebaseapp.com',
    storageBucket: 'ff-frontline.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkv-vrSOuW16kyx3lcBcElCuN7GkDEYjg',
    appId: '1:278339723370:android:79f592513b11247210ea13',
    messagingSenderId: '278339723370',
    projectId: 'ff-frontline',
    storageBucket: 'ff-frontline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIb-NYfCvm073VkXGpwJbQ1efKJbUb1Q',
    appId: '1:278339723370:ios:74788acef3bd977d10ea13',
    messagingSenderId: '278339723370',
    projectId: 'ff-frontline',
    storageBucket: 'ff-frontline.appspot.com',
    iosClientId: '278339723370-h7ppqq2f1vfb8j0vrdecs624cdvn7ii2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffFrontline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEIb-NYfCvm073VkXGpwJbQ1efKJbUb1Q',
    appId: '1:278339723370:ios:74788acef3bd977d10ea13',
    messagingSenderId: '278339723370',
    projectId: 'ff-frontline',
    storageBucket: 'ff-frontline.appspot.com',
    iosClientId: '278339723370-h7ppqq2f1vfb8j0vrdecs624cdvn7ii2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffFrontline',
  );
}
